### ISSUE TITLE
Build failing with io.js 3.0.0

### ISSUE THREAD

**Issue by simast** [51Degrees/51degrees.node#23]
`npm install 51degrees` results in an error with the latest io.js 3.0.0:

```
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
```

**Comment by yorkie** [comment]
Thanks for your feedback, currently this repo doesn't support io.js v3.0.0, this would be fixed when I upgrade the nan to `2.0.x`.

**Comment by simast** [comment]
Hey @yorkie, any news or at least an ETA on this issue?

We are planning on using 51Degress device detection solution and would like to adopt the latest io.js for performance reason (as per their recent upgrade to V8 4.4).

The io.js will also soon re-brand as official node.js project, so I think it's important to get this issue sorted out.

**Comment by yorkie** [comment]
Thank you @simast, actually I was working on upgrading the nan to v2, but it failed because the nan v2 starts using a complete newer API, which costs me so many time.

And I will try to fix this again in this week, because I will have a vocation, sorry for the delay :(

**Comment by yorkie** [comment]
BTW, what do you mean by the latest io.js, it's 2.5.0 or 3.2.0, because actually io.js releasing is so that fast.

**Comment by simast** [comment]
> BTW, what do you mean by the "latest io.js", it's 2.5.0 or 3.2.0

I was referring to the latest 3.2.0 right now. It seems the issue appeared with 3.0.0 release as 2.5.0 still works with old nan 1.x module. Thanks for looking into this!

**Comment by yorkie** [comment]
You are welcome, when I fixed this will notify you, I guess I'm work this out in the end of this week, hope this would not be too late for you :)

**Comment by yorkie** [comment]
Hey @simast I have upgraded the NAN to 2.0.0, so that it works with iojs 3.x. Use:

```
$ npm install 51degress@1.8.0
```
